BerrasBio/Models/Showing.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BerrasBio.Models
{
    public class Showing
    {
        public int ID { get; set; }
        [DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime StartTime { get; set; }
        public int MovieID { get; set; }
        public int LoungeID { get; set; }
        public int SeatsLeft { get; set; }
        public Movie Movie { get; set; }
        public Lounge Lounge { get; set; }

        public ICollection<ShowingSeat> ShowingSeats { get; set; }
    }
}

BerrasBio/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BerrasBio.Models;

namespace BerrasBio.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BerrasBio/Controllers/ShowingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BerrasBio.Data;
using BerrasBio.Models;

namespace BerrasBio.Controllers
{
    public class ShowingsController : Controller
    {
        private readonly CinemaContext _context;

        public ShowingsController(CinemaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string sortOrder)
        {
            ViewData["StartSortParm"] = sortOrder == "Time" ? "time_desc" : "Time";
            ViewData["MovieTitleSortParm"] = String.IsNullOrEmpty(sortOrder) ? "movietitle_desc" : "";
            ViewData["TimespanSortParm"] = sortOrder == "Timespan" ? "timespan_desc" : "Timespan";
            ViewData["LoungeSortParm"] = sortOrder == "LoungeID" ? "lounge_desc" : "LoungeID";
            ViewData["SeatsSortParm"] = sortOrder == "Seats" ? "seat_desc" : "Seats";
            ViewData["SeatsLeftSortParm"] = sortOrder == "SeatsLeft" ? "seatleft_desc" : "SeatsLeft";

            DateTime today = DateTime.Today;
            ViewData["DateToDay"] = today.ToString("yyyy-MM-dd");

            var showings = from s in _context.Showings
                           .Include(m => m.Movie)
                           .Include(l => l.Lounge)
                           select s;

            switch (sortOrder)
            {
                case "Time":
                    showings = showings.OrderBy(s => s.StartTime);
                    break;

                case "time_desc":
                    showings = showings.OrderByDescending(s => s.StartTime);
                    break;

                case "movietitle_desc":
                    showings = showings.OrderBy(m => m.Movie.Title);
                    break;

                case "Timespan":
                    showings = showings.OrderBy(s => s.Movie.TimeSpan);
                    break;

                case "timespan_desc":
                    showings = showings.OrderByDescending(s => s.Movie.TimeSpan);
                    break;

                case "LoungeID":
                    showings = showings.OrderBy(s => s.LoungeID);
                    break;

                case "lounge_desc":
                    showings = showings.OrderBy(s => s.LoungeID);
                    break;

                case "Seats":
                    showings = showings.OrderByDescending(s => s.Lounge.NrOfSeat);
                    break;

                case "seats_desc":
                    showings = showings.OrderByDescending(s => s.Lounge.NrOfSeat);
                    break;

               case "SeatsLeft":
                    showings = showings.OrderByDescending(s => s.SeatsLeft);
                    break;

                case "seatsleft_desc":
                    showings = showings.OrderByDescending(s => s.SeatsLeft);
                    break;

                default:
                    showings = showings.OrderBy(s => s.StartTime);
                    break;

            }


            return View(await showings.AsNoTracking().ToListAsync());

        }

        // GET: Showings/Book/4
        [HttpGet]
        public ActionResult Book(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var selectedShowing = _context.Showings
           .Include(a => a.Lounge)
           .Include(m => m.Movie)
           .SingleOrDefault(m => m.ID == id);

            DateTime today = DateTime.Today;
            ViewData["DateToDay"] = today.ToString("yyyy-MM-dd");

            ViewData["SeatsLeft"] = selectedShowing.SeatsLeft < 12 ? selectedShowing.SeatsLeft : 12;

            ViewData["BookAvailable"] = selectedShowing.SeatsLeft;

            var ticketMoviePrice = selectedShowing.Movie.TicketPrice;

            var loungeTicketFee = (decimal)selectedShowing.Lounge.TicketFee;

            ViewData["TicketPrice"] = ticketMoviePrice * loungeTicketFee;

            if (selectedShowing == null)
            {
                return NotFound();
            }

            return View(selectedShowing);
        }

        // POST: Showings/Book/4
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Book(int? id, int nrOfTickets)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookedShowing = _context.Showings
               .Include(a => a.Lounge)
               .Include(m => m.Movie)
               .SingleOrDefault(m => m.ID == id);

             bookedShowing.SeatsLeft -= nrOfTickets;

            _context.Update(bookedShowing);
            _context.SaveChanges();

            if (bookedShowing == null)
            {
                return NotFound();
            }

            return RedirectToAction("Booked", new {id, nrOfTickets });

            //return RedirectToAction(nameof(Booked), nameof(ShowingsController), ""+id +"/"+nrOfTickets);
            //    /Showings/Booked#5/2

            //return View(bookedShowing);
        }

        [HttpGet]
        public ActionResult Booked(int? id, int? nrOfTickets)
        {
            if (id == null || nrOfTickets == null)
            {
                return NotFound();
            }

            var selectedShowing = _context.Showings
           .Include(a => a.Lounge)
           .Include(m => m.Movie)
           .SingleOrDefault(m => m.ID == id);

            DateTime today = DateTime.Today;
            ViewData["DateToDay"] = today.ToString("yyyy-MM-dd");

            ViewData["NrOfTIckets"] = nrOfTickets;

            var ticketMoviePrice = selectedShowing.Movie.TicketPrice;

            var loungeTicketFee = (decimal)selectedShowing.Lounge.TicketFee;

            ViewData["TicketPrice"] = ticketMoviePrice * loungeTicketFee;

            ViewData["TotalTicketPrice"] = ticketMoviePrice * loungeTicketFee * nrOfTickets;


            if (selectedShowing == null)
            {
                return NotFound();
            }

            return View(selectedShowing);
        }

        /*
        // GET: Showings/Book/4
        public async Task<IActionResult> Book(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            DateTime today = DateTime.Today;
            ViewData["DateToDay"] = today.ToString("yyyy-MM-dd");

            //var showing = await _context.Showings.SingleOrDefaultAsync(m => m.ID == id);

            var showing = await _context.Showings
              .Include(s => s.Lounge)
              .Include(s => s.Movie)
              .SingleOrDefaultAsync(m => m.ID == id);

            if (showing == null)
            {
                return NotFound();
            }
            ViewData["LoungeID"] = new SelectList(_context.Lounges, "ID", "ID", showing.LoungeID);
            ViewData["MovieID"] = new SelectList(_context.Movies, "ID", "ID", showing.MovieID);
    
           return View(showing);
        }

  


        

        /*
          public async Task<IActionResult> Index(int? id)
          {
              if (id == null)
              {
                  return NotFound();
              }

              var showings = await _context.Showings
                  .Include(s => s.Movie)
                      .Include(e => e.Lounge)
                  .AsNoTracking()
                  .SingleOrDefaultAsync(m => m.ID == id);

              if (showings == null)
              {
                  return NotFound();
              }

              return View(showings);
          }


          // GET: Showings
          public async Task<IActionResult> Index()
          {
              var cinemaContext = _context.Showings.Include(s => s.Lounge).Include(s => s.Movie);
              return View(await cinemaContext.ToListAsync());
          }

          */
        // GET: Showings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var showing = await _context.Showings
                .Include(s => s.Lounge)
                .Include(s => s.Movie)
                .SingleOrDefaultAsync(m => m.ID == id);

            var ticketMoviePrice = showing.Movie.TicketPrice;

            var loungeTicketFee = (decimal)showing.Lounge.TicketFee;

            ViewData["TicketPrice"] = ticketMoviePrice * loungeTicketFee;

            DateTime today = DateTime.Today;
            ViewData["DateToDay"] = today.ToString("yyyy-MM-dd");

            if (showing == null)
            {
                return NotFound();
            }

            return View(showing);
        }

        // GET: Showings/Create
        public IActionResult Create()
        {
            ViewData["LoungeID"] = new SelectList(_context.Lounges, "ID", "ID");
            ViewData["MovieID"] = new SelectList(_context.Movies, "ID", "ID");
            return View();
        }

        // POST: Showings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,StartTime,MovieID,LoungeID,SeatsLeft")] Showing showing)
        {
            if (ModelState.IsValid)
            {
                _context.Add(showing);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

BerrasBio/Views/Showings/Book.cshtml
@model BerrasBio.Models.Showing

@{
    ViewData["Title"] = "Book";
}

<body class="bookPage">

    <h3>Book today: @ViewData["DateToDay"]</h3>

    <hr />

    <div>
        <h3>@Html.DisplayFor(model => model.Movie.Title)</h3>
        <dl class="dl-horizontal">
            <dt>
                Start
            </dt>
            <dd>
                @Html.DisplayFor(model => model.StartTime)
            </dd>
            <dt>
                Lounge
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Lounge.ID)
            </dd>
            <dt>
                Seats left
            </dt>
            <dd>
                @Html.DisplayFor(model => model.SeatsLeft)

            </dd>
            <dt>
                Ticket price
            </dt>
            <dd>
                @ViewData["TicketPrice"] Sek
            </dd>
            <dt>
                Tickets (max 12)
            </dt>
            <dd>

                @using (Html.BeginForm("Book"))
        {
            <input type="number" name="nrOfTickets" min="1" max=@ViewBag.SeatsLeft value="1" />
            <input type="submit" value="Book now" />
}
            </dd>
        </dl>
    </div>



    <div>
        <a asp-action="Index">Back to Movie List</a>
    </div>
</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BerrasBio/Views/Showings/Booked.cshtml
@model BerrasBio.Models.Showing

@{
    ViewData["Title"] = "Booked";
}

<body class="bookedPage">

    <h3>Confirm Book - @ViewData["DateToDay"]</h3>

    <hr />

    <div>
        <h3>@Html.DisplayFor(model => model.Movie.Title)</h3>
        <dl class="dl-horizontal">
            <dt>
                Start
            </dt>
            <dd>
                @Html.DisplayFor(model => model.StartTime)
            </dd>
            <dt>
                Lounge
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Lounge.ID)
            </dd>
            <dt>
                Tickets
            </dt>
            <dd>
                @ViewBag.NrOfTIckets
            </dd>
            <dt>
                Ticket price
            </dt>
            <dd>
                @ViewData["TicketPrice"] Sek
            </dd>
            <dt>
                Total ticket price
            </dt>
            <dd>
                @ViewData["TotalTicketPrice"] Sek
            </dd>
        </dl>
    </div>

        <hr />
        <h3>Thank you!</h3>
        <br>
        <h3>Enjoy the movie!</h3>
        <hr />

    <div>
        <a asp-action="Index">Back to Movie List</a>
    </div>
</body>

BerrasBio/Views/Showings/Create.cshtml
@model BerrasBio.Models.Showing

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Showing</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieID" class="control-label"></label>
                <select asp-for="MovieID" class ="form-control" asp-items="ViewBag.MovieID"></select>
            </div>
            <div class="form-group">
                <label asp-for="LoungeID" class="control-label"></label>
                <select asp-for="LoungeID" class ="form-control" asp-items="ViewBag.LoungeID"></select>
            </div>
            <div class="form-group">
                <label asp-for="SeatsLeft" class="control-label"></label>
                <input asp-for="SeatsLeft" class="form-control" />
                <span asp-validation-for="SeatsLeft" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BerrasBio/Views/Showings/Delete.cshtml
@model BerrasBio.Models.Showing

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Showing</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SeatsLeft)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SeatsLeft)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Lounge)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Lounge.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Movie.ID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BerrasBio/Views/Showings/Details.cshtml
@model BerrasBio.Models.Showing

@{
    ViewData["Title"] = "Details";
}

<body class="infoPage">

    <h3>Movie Information - @ViewData["DateToDay"]</h3>

    <hr />

    <div>

        <dl class="dl-horizontal">
            <dt>
                Movie title
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Movie.Title)
            </dd>
            <dt>
                Movie info
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Movie.Info)
            </dd>
            <dt>
                Start
            </dt>
            <dd>
                @Html.DisplayFor(model => model.StartTime)
            </dd>
            <dt>
                Timespan
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Movie.TimeSpan)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Lounge)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Lounge.ID)
            </dd>
            <dt>
                Lounge info
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Lounge.Info)
            </dd>
            <dt>
                Seats
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Lounge.NrOfSeat)
            </dd>
            <dt>
                Seats left
            </dt>
            <dd>
                @Html.DisplayFor(model => model.SeatsLeft)
            </dd>
            <dt>
                Ticket price
            </dt>
            <dd>
                @ViewData["TicketPrice"] Sek
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
    </body>

BerrasBio/Views/Showings/Edit.cshtml
@model BerrasBio.Models.Showing

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Showing</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieID" class="control-label"></label>
                <select asp-for="MovieID" class="form-control" asp-items="ViewBag.MovieID"></select>
                <span asp-validation-for="MovieID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoungeID" class="control-label"></label>
                <select asp-for="LoungeID" class="form-control" asp-items="ViewBag.LoungeID"></select>
                <span asp-validation-for="LoungeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeatsLeft" class="control-label"></label>
                <input asp-for="SeatsLeft" class="form-control" />
                <span asp-validation-for="SeatsLeft" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BerrasBio/Views/Showings/Home.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<body class="startPage">


    <div class="StartText">
        <br>
        <br>

        <h2>Welcome to Berras Bio</h2>

        <a asp-area="" asp-controller="Showings" asp-action="Index">Movie Today</a>

    </div>


</body>

BerrasBio/Views/Showings/Index.cshtml
@model IEnumerable<BerrasBio.Models.Showing>

@{
    ViewData["Title"] = "Index";
}

<body class="moviePage">

    <h2>Movies today - @ViewData["DateToDay"]</h2>


    <table class="table">
        <thead>
            <tr>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["TimeSortParm"]" title="Sort Start time">Start</a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["MovieTitleSortParm"]" title="Sort Movie title">Movie title</a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["TimespanSortParm"]" title="Sort timespan">Timespan</a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["LoungeSortParm"]" title="sort lounge nr">Lounge</a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["SeatsSortParm"]" title="Sort seats">Seats</a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["SeatsLeftSortParm"]" title="Sort seats left">Seats left</a>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="@(item.SeatsLeft > 0 ? "movieInfo" : "movieBooked")">
                    <td>
                        <a asp-action="Details" asp-route-id="@item.ID" class="@(item.SeatsLeft > 0 ? "movieInfo" : "movieBooked")" title="Details"> @Html.DisplayFor(modelItem => item.StartTime)</a> 
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.ID" class="@(item.SeatsLeft > 0 ? "movieInfo" : "movieBooked")" title="Details"> @Html.DisplayFor(modelItem => item.Movie.Title)</a>
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.ID" class="@(item.SeatsLeft > 0 ? "movieInfo" : "movieBooked")" title="Details"> @Html.DisplayFor(modelItem => item.Movie.TimeSpan)</a>
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.ID" class="@(item.SeatsLeft > 0 ? "movieInfo" : "movieBooked")" title="Details"> @Html.DisplayFor(modelItem => item.LoungeID)</a>
                        
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.ID" class="@(item.SeatsLeft > 0 ? "movieInfo" : "movieBooked")" title="Details"> @Html.DisplayFor(modelItem => item.Lounge.NrOfSeat)</a>
                        
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.ID" class="@(item.SeatsLeft > 0 ? "movieInfo" : "movieBooked")" title="Details"> @Html.DisplayFor(modelItem => item.SeatsLeft)</a>
                        
                    </td>

                    <td>
                        @{var nrSeats = item.SeatsLeft;
                        }

                        @if (nrSeats > 0)
                        {
                            <a asp-action="Book" asp-route-id="@item.ID" title="Book tickets">Book</a>
                        }
                        <!-- |
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a>

                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                            -->

                    </td>
                </tr>
            }
        </tbody>
    </table>
    
    <div>
        <a asp-area="" asp-controller="Home" asp-action="Index">Back to Start Page</a>
        <!--
    <a asp-area="" asp-controller="Showing" asp-action="Home">Back to Start Page</a>
        -->

    </div>

    
</body>